# Generated by Django 3.1.4 on 2020-12-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=200)),
                ('file_type', models.CharField(choices=[('mp3', 'mp3'), ('wav', 'wav'), ('ogg', 'ogg')], max_length=10)),
            ],
        ),
    ]
