# Generated by Django 3.1.4 on 2020-12-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0002_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(default='Untitled', max_length=500),
        ),
    ]
