# Generated by Django 3.1.4 on 2020-12-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0003_auto_20201225_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnapprovedArtwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=500)),
                ('description', models.TextField()),
                ('artist', models.CharField(default='Unknown', max_length=500)),
                ('file', models.FileField(upload_to='unapproved-artworks/')),
            ],
        ),
    ]
