# Generated by Django 3.1.4 on 2020-12-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0004_unapprovedartwork'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnapprovedArtwork',
        ),
        migrations.AddField(
            model_name='artwork',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
