# Generated by Django 3.1.4 on 2020-12-30 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0005_auto_20201225_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='songs/'),
            preserve_default=False,
        ),
    ]
