# Generated by Django 3.1.4 on 2020-12-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0006_auto_20201230_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='file',
            field=models.FileField(upload_to='artworks/'),
        ),
    ]
